-- Run as DB superuser (postgres) if mindex role cannot self-grant.
GRANT USAGE ON SCHEMA bio TO mindex;
GRANT USAGE ON SCHEMA obs TO mindex;
GRANT USAGE ON SCHEMA core TO mindex;
GRANT USAGE ON SCHEMA media TO mindex;
GRANT USAGE ON SCHEMA ledger TO mindex;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA bio TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA obs TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA media TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ledger TO mindex;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bio TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA obs TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA media TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO mindex;
