-- Grant MINDEX API role access to ledger schema (anchors, DAG nodes).
-- Safe to re-run.
BEGIN;

GRANT USAGE ON SCHEMA ledger TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ledger TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO mindex;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mindex;

GRANT USAGE ON SCHEMA media TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA media TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA media TO mindex;

COMMIT;
