-- Extended grants for Encyclopedia / bio plane (handoff 002, 007).
BEGIN;

GRANT USAGE ON SCHEMA bio TO mindex;
GRANT USAGE ON SCHEMA obs TO mindex;
GRANT USAGE ON SCHEMA core TO mindex;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA bio TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA obs TO mindex;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO mindex;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bio TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA obs TO mindex;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core TO mindex;

ALTER DEFAULT PRIVILEGES IN SCHEMA bio
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mindex;
ALTER DEFAULT PRIVILEGES IN SCHEMA obs
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mindex;

COMMIT;
